#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
molvis.py - Professional 2D molecular visualization with matplotlib
Ball-and-stick models (CPK colors), hybrid orbitals, electron clouds, pi orbitals.
All constants imported from utils.py (SINGLE SOURCE) - no redefinition.
"""
import json
import os
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Ellipse

# Import shared constants from utils (SINGLE SOURCE - do NOT redefine)
from .utils import (
    CPK_COLORS, ATOMIC_PROPERTIES, DEFAULT_COLOR, DEFAULT_RADIUS,
    get_cpk_color, get_atomic_radius, get_element_name,
    BOND_SINGLE, BOND_DOUBLE, BOND_TRIPLE, BOND_AROMATIC, get_bond_name,
    HYBRID_SP, HYBRID_SP2, HYBRID_SP3, get_hybrid_angle,
)


def load_mol(json_path):
    """Load molecule from JSON (generated by generate_coords.js / RDKit.js)."""
    with open(json_path, 'r') as f:
        return json.load(f)

def load_mol_by_name(name, mol_dir='molecule_outputs'):
    """Load molecule by name from molecule_outputs directory."""
    return load_mol(os.path.join(mol_dir, f'{name}.json'))


def draw_bond(ax, x1, y1, x2, y2, bond_type=BOND_SINGLE, color='#555555', lw=2.5):
    """Draw a chemical bond. Uses bond type constants from utils."""
    dx, dy = x2 - x1, y2 - y1
    length = np.sqrt(dx**2 + dy**2)
    if length < 1e-6:
        return
    nx, ny = -dy / length, dx / length

    if bond_type == BOND_SINGLE:
        ax.plot([x1, x2], [y1, y2], color=color, linewidth=lw, solid_capstyle='round', zorder=2)
    elif bond_type == BOND_DOUBLE:
        offset = 0.08
        for sgn in [1, -1]:
            ax.plot([x1 + nx*offset*sgn, x2 + nx*offset*sgn],
                    [y1 + ny*offset*sgn, y2 + ny*offset*sgn],
                    color=color, linewidth=lw*0.7, solid_capstyle='round', zorder=2)
    elif bond_type == BOND_TRIPLE:
        offset = 0.1
        ax.plot([x1, x2], [y1, y2], color=color, linewidth=lw*0.6, solid_capstyle='round', zorder=2)
        for sgn in [1, -1]:
            ax.plot([x1 + nx*offset*sgn, x2 + nx*offset*sgn],
                    [y1 + ny*offset*sgn, y2 + ny*offset*sgn],
                    color=color, linewidth=lw*0.6, solid_capstyle='round', zorder=2)
    elif bond_type == BOND_AROMATIC:
        ax.plot([x1, x2], [y1, y2], color=color, linewidth=lw, solid_capstyle='round', zorder=2)


def draw_ball_stick(ax, mol, center_x=0, center_y=0, scale=1.0,
                     atom_labels=False, bond_color='#555555', highlight_atoms=None,
                     show_hydrogens=True):
    """Draw a professional ball-and-stick model."""
    atoms = mol['atoms']
    bonds = mol['bonds']

    if not show_hydrogens:
        atom_indices = {a['index'] for a in atoms if a['element'] != 'H'}
        atoms = [a for a in atoms if a['element'] != 'H']
        bonds = [b for b in bonds if b['atom1'] in atom_indices and b['atom2'] in atom_indices]

    xs = [a['x'] for a in atoms]
    ys = [a['y'] for a in atoms]
    cx, cy = np.mean(xs), np.mean(ys)

    for bond in bonds:
        a1 = next(a for a in atoms if a['index'] == bond['atom1'])
        a2 = next(a for a in atoms if a['index'] == bond['atom2'])
        x1 = center_x + (a1['x'] - cx) * scale
        y1 = center_y + (a1['y'] - cy) * scale
        x2 = center_x + (a2['x'] - cx) * scale
        y2 = center_y + (a2['y'] - cy) * scale
        draw_bond(ax, x1, y1, x2, y2, bond_type=bond['bondType'],
                  color=bond_color, lw=2.2 * scale)

    for atom in atoms:
        elem = atom['element']
        color = get_cpk_color(elem)
        r = get_atomic_radius(elem, scale=scale)
        x = center_x + (atom['x'] - cx) * scale
        y = center_y + (atom['y'] - cy) * scale

        ax.add_patch(Circle((x, y), r * 1.15, facecolor='#222222', alpha=0.25, zorder=3))
        ax.add_patch(Circle((x, y), r, facecolor=color, edgecolor='#333333',
                             linewidth=0.5, zorder=4))
        ax.add_patch(Circle((x - r*0.3, y + r*0.3), r*0.35, facecolor='white',
                             alpha=0.4, zorder=5))

        if highlight_atoms and atom['index'] in highlight_atoms:
            ax.add_patch(Circle((x, y), r * 1.6, facecolor='none', edgecolor='#FFD700',
                                 linewidth=2, linestyle='--', zorder=6))

        if atom_labels and elem != 'H':
            text_color = 'white' if elem in ['C', 'N', 'O', 'S', 'Cl', 'Br', 'I'] else 'black'
            ax.text(x, y, elem, ha='center', va='center', fontsize=5*scale,
                    color=text_color, fontweight='bold', zorder=7)


def draw_sp2_orbitals(ax, cx, cy, scale=1.0, color='#FF6B6B', alpha=0.3):
    """Draw sp2 hybrid orbitals: 3 trigonal planar lobes (120 deg) + p_z orbital."""
    angle = get_hybrid_angle(HYBRID_SP2)
    start_angle = 90
    for i in range(3):
        deg = start_angle + i * angle
        rad = np.radians(deg)
        lobe_len = 0.6 * scale
        lobe_w = 0.25 * scale
        ex = cx + np.cos(rad) * lobe_len * 0.5
        ey = cy + np.sin(rad) * lobe_len * 0.5
        ax.add_patch(Ellipse((ex, ey), lobe_len, lobe_w, angle=np.degrees(rad),
                             facecolor=color, alpha=alpha, edgecolor=color, linewidth=0.5, zorder=1))
    p_len = 0.5 * scale
    p_w = 0.2 * scale
    for dy in [-p_len*0.6, p_len*0.6]:
        ax.add_patch(Ellipse((cx, cy + dy), p_w, p_len*0.8, angle=0,
                             facecolor='#9B59B6', alpha=alpha*0.8, edgecolor='#9B59B6',
                             linewidth=0.5, zorder=1))

def draw_sp3_orbitals(ax, cx, cy, scale=1.0, color='#3498DB', alpha=0.3):
    """Draw sp3 hybrid orbitals: 4 tetrahedral lobes (109.5 deg), 2D projection."""
    angles = [45, 135, 225, 315]
    sizes = [1.0, 0.8, 0.8, 1.0]
    for deg, sz in zip(angles, sizes):
        rad = np.radians(deg)
        lobe_len = 0.55 * scale * sz
        lobe_w = 0.22 * scale * sz
        ex = cx + np.cos(rad) * lobe_len * 0.5
        ey = cy + np.sin(rad) * lobe_len * 0.5
        ax.add_patch(Ellipse((ex, ey), lobe_len, lobe_w, angle=np.degrees(rad),
                             facecolor=color, alpha=alpha*sz, edgecolor=color, linewidth=0.5, zorder=1))

def draw_sp_orbitals(ax, cx, cy, scale=1.0, color='#E74C3C', alpha=0.3):
    """Draw sp hybrid orbitals: 2 linear lobes (180 deg) + 2 p orbitals perpendicular."""
    angle = get_hybrid_angle(HYBRID_SP)
    for i in range(2):
        deg = i * angle
        rad = np.radians(deg)
        lobe_len = 0.65 * scale
        lobe_w = 0.22 * scale
        ex = cx + np.cos(rad) * lobe_len * 0.5
        ey = cy + np.sin(rad) * lobe_len * 0.5
        ax.add_patch(Ellipse((ex, ey), lobe_len, lobe_w, angle=np.degrees(rad),
                             facecolor=color, alpha=alpha, edgecolor=color, linewidth=0.5, zorder=1))
    for rot in [0, 90]:
        p_len = 0.45 * scale
        p_w = 0.18 * scale
        for sgn in [-1, 1]:
            dx = sgn * p_len * 0.55 * np.cos(np.radians(rot))
            dy = sgn * p_len * 0.55 * np.sin(np.radians(rot))
            ax.add_patch(Ellipse((cx+dx, cy+dy), p_w, p_len, angle=rot,
                                 facecolor='#9B59B6', alpha=alpha*0.7, edgecolor='#9B59B6',
                                 linewidth=0.5, zorder=1))


def draw_electron_cloud(ax, cx, cy, scale=1.0, color='#E74C3C', n_levels=5):
    """Draw electron cloud as concentric probability density contours."""
    for i in range(n_levels, 0, -1):
        r = 0.15 * scale * i
        alpha = 0.08 * (n_levels - i + 1)
        ax.add_patch(Circle((cx, cy), r, facecolor=color, alpha=alpha,
                             edgecolor='none', zorder=0))

def draw_pi_orbital(ax, cx, cy, scale=1.0, color='#9B59B6', alpha=0.35):
    """Draw pi orbital (p_z): two lobes above/below nodal plane."""
    lobe_len = 0.5 * scale
    lobe_w = 0.35 * scale
    for dy in [-lobe_len*0.55, lobe_len*0.55]:
        ax.add_patch(Ellipse((cx, cy + dy), lobe_w, lobe_len, angle=0,
                             facecolor=color, alpha=alpha, edgecolor=color, linewidth=0.8, zorder=1))
    ax.plot([cx - lobe_w*0.8, cx + lobe_w*0.8], [cy, cy], color=color,
            linewidth=0.8, linestyle='--', alpha=0.5, zorder=1)


def draw_fret(ax, donor_x, donor_y, acceptor_x, acceptor_y, scale=1.0, color='#FFD700'):
    """Draw FRET energy transfer: dashed arrow from donor to acceptor + electron cloud."""
    ax.annotate('', xy=(acceptor_x, acceptor_y), xytext=(donor_x, donor_y),
                arrowprops=dict(arrowstyle='->', color=color, lw=2, linestyle='dashed'))
    mid_x = (donor_x + acceptor_x) / 2
    mid_y = (donor_y + acceptor_y) / 2 + 0.2 * scale
    ax.text(mid_x, mid_y, 'FRET', ha='center', fontsize=7*scale, color='#B8860B', fontweight='bold')
    draw_electron_cloud(ax, acceptor_x, acceptor_y, scale=scale, color=color, n_levels=4)


def plot_molecule(mol, title='', scale=1.0, atom_labels=True, show_hydrogens=True,
                  figsize=(6, 6), save_path=None):
    """Create a standalone matplotlib figure of a ball-and-stick molecule."""
    fig, ax = plt.subplots(figsize=figsize)
    ax.set_aspect('equal')
    ax.axis('off')
    if title:
        ax.set_title(title, fontsize=12, fontweight='bold')
    draw_ball_stick(ax, mol, scale=scale, atom_labels=atom_labels, show_hydrogens=show_hydrogens)
    plt.tight_layout()
    if save_path:
        fig.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f'Saved: {save_path}')
    return fig, ax