#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
render_3d.py - Generate interactive 3D molecular HTML using py3Dmol
Integrates 3Dmol repository approach (py3Dmol) with RDKit.js coordinates.
Reads molecule JSON from generate_coords.js output, converts to MOL block,
renders interactive 3D HTML (ball-and-stick / spacefill / wireframe).

Usage:
  python render_3d.py --mol molecule_outputs/PET_terephthalic.json --style sphere+stick
  python render_3d.py --smiles "c1ccccc1" --name benzene --style stick
"""
import json
import os
import sys
import argparse

try:
    import py3Dmol
    HAS_PY3DMOL = True
except ImportError:
    HAS_PY3DMOL = False
    print("Warning: py3Dmol not installed. Install with: pip install py3Dmol")
    print("Falling back to static HTML with 3Dmol.js CDN...")


def mol_json_to_molblock(mol_data):
    """Convert molecule JSON (from generate_coords.js) to MOL V2000 block string."""
    atoms = mol_data['atoms']
    bonds = mol_data['bonds']
    n_atoms = len(atoms)
    n_bonds = len(bonds)

    lines = []
    lines.append(mol_data.get('name', 'molecule'))
    lines.append('  Generated by molecular-visualization skill')
    lines.append('')
    lines.append(f'{n_atoms:>3d}{n_bonds:>3d}  0  0  0  0  0  0  0  0999 V2000')

    for atom in atoms:
        x, y, z = atom['x'], atom['y'], atom.get('z', 0.0)
        elem = atom['element']
        lines.append(f'{x:>10.4f}{y:>10.4f}{z:>10.4f} {elem:<3s} 0  0  0  0  0  0  0  0  0  0  0  0')

    for bond in bonds:
        a1, a2, bt = bond['atom1'], bond['atom2'], bond['bondType']
        lines.append(f'{a1:>3d}{a2:>3d}{bt:>3d}  0  0  0  0')

    lines.append('M  END')
    return '\n'.join(lines)


def render_3d_html(mol_data, style='sphere+stick', width=600, height=500,
                    title='', output_path=None):
    """Generate interactive 3D HTML using py3Dmol (or 3Dmol.js CDN fallback).

    Styles:
      - 'sphere+stick': ball-and-stick (default)
      - 'stick': stick only
      - 'sphere': spacefill (CPK spheres)
      - 'line': wireframe
      - 'cartoon': protein cartoon (for biomolecules)
    """
    molblock = mol_json_to_molblock(mol_data)

    style_map = {
        'sphere+stick': {'sphere': {'radius': 0.3}, 'stick': {'radius': 0.1}},
        'stick':        {'stick': {'radius': 0.15}},
        'sphere':       {'sphere': {'radius': 0.5}},
        'line':         {'line': {'linewidth': 1}},
        'cartoon':      {'cartoon': {'color': 'spectrum'}},
    }
    style_dict = style_map.get(style, style_map['sphere+stick'])

    if HAS_PY3DMOL:
        view = py3Dmol.view(width=width, height=height)
        view.addModel(molblock, 'mol')
        view.setStyle({}, style_dict)
        view.zoomTo()
        if title:
            view.addLabel(title, {'fontSize': 14, 'fontColor': 'black',
                                  'position': {'x': 10, 'y': 10}, 'useScreen': True})
        html_content = view.write_html()
    else:
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>{title or '3D Molecule'}</title>
    <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
    <style>
        body {{ margin: 0; font-family: Arial, sans-serif; }}
        #viewer {{ width: {width}px; height: {height}px; position: relative; }}
        .title {{ position: absolute; top: 10px; left: 10px; font-size: 14px;
                  font-weight: bold; color: #333; z-index: 10; }}
    </style>
</head>
<body>
    <div id="viewer">
        <div class="title">{title}</div>
    </div>
    <script>
        var molData = `{molblock}`;
        var viewer = $3Dmol.createViewer("viewer");
        viewer.addModel(molData, "mol");
        viewer.setStyle({{}}, {json.dumps(style_dict)});
        viewer.zoomTo();
        viewer.render();
    </script>
</body>
</html>"""

    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
        print(f'3D HTML saved: {output_path}')

    return html_content


def render_multi_3d_html(mol_list, style='sphere+stick', cols=3, width=400, height=350,
                          output_path=None):
    """Render multiple molecules in a grid layout (interactive 3D HTML)."""
    n = len(mol_list)
    rows = (n + cols - 1) // cols

    cards_html = ''
    for i, (mol_data, title) in enumerate(mol_list):
        molblock = mol_json_to_molblock(mol_data)
        div_id = f'mol_{i}'
        cards_html += f'''
        <div style="display:inline-block; margin:5px; vertical-align:top;">
            <div id="{div_id}" style="width:{width}px; height:{height}px; position:relative; border:1px solid #ddd;"></div>
            <div style="text-align:center; font-size:12px; font-weight:bold; margin-top:3px;">{title}</div>
        </div>
        <script>
            (function() {{
                var viewer = $3Dmol.createViewer("{div_id}");
                viewer.addModel(`{molblock}`, "mol");
                viewer.setStyle({{}}, {json.dumps({'sphere': {'radius': 0.3}, 'stick': {'radius': 0.1}} if style=='sphere+stick' else {'stick': {'radius': 0.15}})});
                viewer.zoomTo();
                viewer.render();
            }})();
        </script>'''

    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>3D Molecule Gallery</title>
    <script src="https://3Dmol.org/build/3Dmol-min.js"></script>
    <style>body {{ font-family: Arial, sans-serif; padding: 10px; }}</style>
</head>
<body>
    <h2>3D Molecule Gallery ({n} molecules)</h2>
    {cards_html}
</body>
</html>"""

    if output_path:
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f'3D gallery saved: {output_path} ({n} molecules, {rows}x{cols} grid)')

    return html


def main():
    parser = argparse.ArgumentParser(description='Render interactive 3D molecular HTML')
    parser.add_argument('--mol', help='Path to molecule JSON (from generate_coords.js)')
    parser.add_argument('--smiles', help='SMILES string (requires generate_coords.js to pre-generate)')
    parser.add_argument('--name', help='Molecule name (for output file)')
    parser.add_argument('--style', default='sphere+stick',
                        choices=['sphere+stick', 'stick', 'sphere', 'line', 'cartoon'],
                        help='Rendering style')
    parser.add_argument('--width', type=int, default=600)
    parser.add_argument('--height', type=int, default=500)
    parser.add_argument('--output', help='Output HTML path')
    args = parser.parse_args()

    if args.mol:
        with open(args.mol, 'r') as f:
            mol_data = json.load(f)
        title = mol_data.get('name', args.name or 'molecule')
        output = args.output or f'{title}_3D.html'
        render_3d_html(mol_data, style=args.style, width=args.width,
                        height=args.height, title=title, output_path=output)
    else:
        print("Specify --mol <path.json>")
        sys.exit(1)


if __name__ == '__main__':
    main()